databases:
  - name: libraryManagementSystemdb
    plan: free
    databaseName: library-database
    user: libraryManagementSystem

services:
  - type: web
    plan: free
    name: libraryManagementSystem
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn libraryManagementSystem.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: libraryManagementSystemdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4