databases:
  - name: lms-database
    plan: free
    databaseName: DATABASE_NAME
    user: USERNAME

services:
  - type: web
    plan: free
    name: lms-db
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn libraryManagementSystem.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: library-database
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4