databases:
  - name: lms-db
    plan: free
    databaseName: 'lms_db_3v7h'
    user: 'lms_db_3v7h_user'

services:
  - type: web
    plan: free
    name: lms-db
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn libraryManagementSystem.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: lms-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4