# Generated by Django 5.1.1 on 2024-10-07 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryManagementSystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date_due',
            field=models.DateField(blank=True),
        ),
    ]
