# Generated by Django 5.1.1 on 2024-10-14 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryManagementSystem', '0002_alter_transaction_date_due'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='roles',
            field=models.ManyToManyField(default='member', related_name='users', to='libraryManagementSystem.role'),
        ),
    ]
